# Generated by Django 3.0.3 on 2020-02-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juhe', '0003_auto_20200227_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='focus_cities',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='focus_constructions',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='focus_stocks',
        ),
    ]
