# Generated by Django 3.0.3 on 2020-02-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juhe', '0004_auto_20200227_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='focus_cities',
            field=models.TextField(default=[]),
        ),
        migrations.AddField(
            model_name='user1',
            name='focus_constructions',
            field=models.TextField(default=[]),
        ),
        migrations.AddField(
            model_name='user1',
            name='focus_stocks',
            field=models.TextField(default=[]),
        ),
    ]
